import streamlit as st
from res_langchain import generate_restaurant

def app():
    st.title("Your Restaurant Muse")

    cuisines = [
        "Italian",
        "Chinese",
        "Indian",
        "Mexican",
        "Japanese",
        "French",
        "Thai",
        "Spanish",
        "Greek",
        "Lebanese",
        "Turkish",
        "Vietnamese",
        "Korean",
        "Brazilian",
        "Moroccan",
        "Ethiopian",
        "Caribbean",
        "American",
        "British",
        "German",
        "Russian",
        "Cuban",
        "Peruvian",
        "Argentinian",
        "Indonesian",
        "Malaysian",
        "Filipino",
        "Pakistani",
        "Bangladeshi",
        "Sri Lankan",
        "Nepalese",
        "Afghan",
        "Persian",
        "Portuguese",
        "Polish",
        "Hungarian",
        "Czech",
        "Austrian",
        "Swiss",
        "Belgian",
        "Dutch",
        "Swedish",
        "Danish",
        "Norwegian",
        "Finnish",
        "Icelandic",
        "Australian",
        "New Zealand",
        "South African",
        "Nigerian",
        "Kenyan",
        "Tanzanian",
        "Ugandan",
        "Ghanaian",
        "Senegalese",
        "Cameroonian",
        "Ivory Coast",
        "Tunisian",
        "Algerian",
        "Egyptian",
        "Saudi Arabian",
        "Syrian",
        "Jordanian",
        "Palestinian",
        "Iraqi",
        "Iranian",
        "Afghan",
        "Uzbek",
        "Kazakh",
        "Mongolian",
        "Tibetan",
        "Bhutanese",
        "Myanmar",
        "Laotian",
        "Cambodian",
        "Singaporean",
        "Hong Kong",
        "Taiwanese",
        "Hawaiian",
        "Californian",
        "Tex-Mex",
        "Southern American",
        "New England",
        "Creole",
        "Cajun",
        "Pacific Northwest",
        "Midwestern American",
        "Puerto Rican",
        "Costa Rican",
        "Guatemalan",
        "Salvadoran",
        "Honduran",
        "Nicaraguan",
        "Panamanian",
        "Chilean",
        "Bolivian",
        "Ecuadorian",
        "Uruguayan",
        "Paraguayan",
        "Colombian",
        "Venezuelan",
        "Guyanese",
        "Surinamese",
        "Trinidadian",
        "Jamaican",
        "Barbadian",
        "Bahamian",
        "Antiguan",
        "Dominican",
        "St Lucian",
        "Grenadian",
        "Bermudian",
        "Haitian",
        "Cuban",
        "Belizean",
        "Luxembourgish",
        "Liechtenstein"
    ]
    
    cuisine = st.sidebar.selectbox("Select your cuisine",cuisines)
    generate = st.sidebar.button("Generate")
    if generate:
        response = generate_restaurant(cuisine)
        st.header(response['restaurant_name'].strip())
        st.write("Cuisine : ",cuisine)
        menu_items = response['menu_items'].strip().split(",")
        st.write("**Menu Items**")
        for item in menu_items:
            st.write(item)

if __name__=="__main__":
    app()